Feature
marcode95/nyt-clone pull request #3
Opened 2020-07-23 15:09 UTC by marcode95

This project was about cloning a New York Times article page and work with floats, flex and grid. It was done by me and Nkiruka.

2020-07-23 19:01 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

####  Hello Team. You did a great job :clap: 

The page looks quite good, and you used both flex, grid, and float :100: 
Your code is really organized, and the class names very descriptive.

#### However, there are still a few aspects that we can improve upon (they are described in the inline comments below). Kindly fix them and then apply for the next review.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-23 19:01 UTC, expjazz commented on index.html
> +                </svg>
- [ ] Great job using an SVG here. The only thing is that it needs to be a link (as is in the original)

2020-07-23 19:01 UTC, expjazz commented on index.html
> +                        </div>
- [ ] Also should be a link (as in the original)

2020-07-23 19:01 UTC, expjazz commented on index.html
> +        </div>
- [ ] It should have a fixed position(like in the original).
![image](https://user-images.githubusercontent.com/61479648/88326066-0e2ee280-ccfc-11ea-8b92-acfcfe1dcdbf.png)

2020-07-23 19:01 UTC, expjazz commented on index.html
> +                </div>
- [ ] Kindly fix this layout.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/88326270-3fa7ae00-ccfc-11ea-9bf9-0289bdc0dc61.png) | ![image](https://user-images.githubusercontent.com/61479648/88326335-4fbf8d80-ccfc-11ea-9415-5d95e7623767.png) |

2020-07-23 19:01 UTC, expjazz commented on index.html
> +                        <p><span>THE UNIVERSE</span>  is just under 14 billion years old.
- [ ] The images could have a little more separation from the text (as in the original). The font also seems bigger.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/88327534-85b14180-ccfd-11ea-85a2-f7e687bf2fd9.png) | ![image](https://user-images.githubusercontent.com/61479648/88327571-91046d00-ccfd-11ea-8977-a6c79af6e0d3.png) |

2020-07-24 10:43 UTC, kitpao approved these changes
# Hi @marcode95 and @enkog 

Wow, congratulations guys! 👏  You did all required changes, your page is looking good and your project is ready to be merged 👍 
I left you 2 **optional** suggestions below 🔽 

### 👏 Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-24 10:43 UTC, kitpao commented on README.md
> +🔗 [New york times page](https://rawcdn.githack.com/marcode95/nyt-clone/16af6b1e94b5dd3f19860a25bdb811782c24cce3/index.html)
- [ ] **[OPTIONAL]** After you merge, update your live demo link ( It is showing your previous version). As a suggestion, so you don't have to be manually updating this link during your code reviews, use the second link (development link) in githack, that one will automatically load your last version in the same branch :)

2020-07-24 10:43 UTC, kitpao commented on index.html
> +                        <img src="./img/editor-pick-3.jpg" alt="editor-pick-3">
- [ ] **OPTIONAL** This image is looking slightly smaller, and I'm noticing it's because you gave all your images a defined width and height. Next time, try to put a containing div only for the image (with the desiderd dimensions), and inside you can put the image with the following styling so the original proportions of the images will be respected and they don't get stretched or cutten:

**CSS:**
```
img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
```

2020-07-24 11:03 UTC, merged